services:
  postgres:
    image: postgres:16-alpine
    container_name: nutrigest-postgres
    environment:
      POSTGRES_DB: nutrigest
      POSTGRES_USER: nutrigest
      POSTGRES_PASSWORD: nutrigest
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
